#!/bin/sh
#
# Statistics about file types in git repo grouped by file extension.
#
# Example output:
#
# $ git-file-stats
#  48 json
#  53 js
#  54 xml
# 106 xsd

git ls-files |           # list files
  grep -Po "(?<=\.)\w+$" |   # match strings and show only matched lines
  sort |                 # sort before counting to avoid group splits
  uniq -c |              # count unique
  sort -n -k 1           # sort naturally by count (first column)
