#!/bin/sh
#
# Statistics about file types in git repo grouped by file extension.
#
# Example output:
#
# $ git-file-stats
#  48 json
#  53 js
#  54 xml
# 106 xsd

git ls-files |           # list files
  xargs -n 1 basename |  # filename without path
  grep "\." |            # filenames with extension
  cut -d . -f 2- |       # extension only (delimit by . and get fields from 2nd)
  sort |                 # sort before counting to avoid group splits
  uniq -c |              # count unique
  sort -n -k 1           # sort naturally by count (first column)
