name: Build Stats

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    # run every Sunday at 22:12 UTC
    - cron: '12 22 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone `gecko-dev`
        run: |
          git clone https://github.com/mozilla/gecko-dev.git

      - run: npm install -g mustache

      - name: Build
        run: |
          mkdir build
          dev/build-data ./gecko-dev > build/data.json
          cat build/data.json
          mustache build/data.json index.mustache > build/index.html
          cat build/index.html
          
      - name: Gather commits by day and file extension statistics
        run: |
          ./01stats.sh gecko-dev build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
